### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by chriso0710** [ihower/rails-pycall-langchain#1]
Hi @ihower, 
nice work and looks good!
This is exactly what I was looking for as an example to combine langchain and rails.
How do you handle sessions and chat history?
Regards
Christian

**Comment by ihower** [comment]
It just simply saves to the DB and loads all chat history for GPT.
https://github.com/ihower/rails-pycall-langchain/blob/main/app/jobs/langchain_chat_job.rb
